### ISSUE TITLE
Does not load .png images

### ISSUE THREAD

**Issue by Zyin055** [CypherpunkSamurai/captioner#1]
Works fine when loading a folder full of .jpg, but seems to ignore .png images.

**Comment by CypherpunkSamurai** [comment]
Yes the image filter is set to .jpg in utility.py.

I'll add png then.

**Comment by CypherpunkSamurai** [comment]
this issue has been fixed by c2bc252be96246865acee449c617437cd9f0c36c. please check and confirm
