### ISSUE TITLE
Crash on caption save

### ISSUE THREAD

**Issue by Zyin055** [CypherpunkSamurai/captioner#2]
Getting this error when clicking the save button (the .txt file is saved correctly):
```
PS C:\Stuff\AI\captioner> python .\run.py
C:/Users/Zyin/Desktop/temp
selected image: C:/Users/Zyin/Desktop/temp\2022-07-26_02-01-23_UTC.jpg
Traceback (most recent call last):
  File "C:\Stuff\AI\captioner\run.py", line 195, in btn_save_caption_clicked
    self.save_caption(caption_path, caption)
  File "C:\Stuff\AI\captioner\run.py", line 204, in save_caption
    print(f"[+] {caption_path}")
NameError: name 'caption_path' is not defined
PS C:\Stuff\AI\captioner>
```

**Comment by CypherpunkSamurai** [comment]
This has been fixed. Please download the update.

**Comment by CypherpunkSamurai** [comment]
This was [fixed](https://github.com/CypherpunkSamurai/captioner/blob/f50976a7ae500b8c95a19ee5090265a09b5c887b/run.py#L209). Please git clone the repo.

I actually was rebasing the history and found this bug. Git pull won't work (or git pull with unrelated history enabled)
