### ISSUE TITLE
Caption textbox not matching saved caption

### ISSUE THREAD

**Issue by dimitri-vs** [CypherpunkSamurai/captioner#3]
**Expected behavior:** Clicking the save button should save the typed in caption to the caption text file.

**Actual behavior:** It doesn't look like it does anything, not sure if there are errors logged but the Ctrl + S still works.

**Steps to reproduce:** See below.

![230221-632-pythonw](https://user-images.githubusercontent.com/74625979/220497575-0b0b6bd1-4033-458c-90d9-107a97e2ce10.gif)

**Comment by dimitri-vs** [comment]
May have been something specific to my env, restarted the PC and it seems to be working normally.

Note that I did the `run.py` -> `run.pyw` change, so not sure if that had an impact.

**Comment by dimitri-vs** [comment]
Ok so I'm still seeing this issue after a restart and going back to using `run.py` to see what's happening in console.

Its kind of subtle but looks like it IS saving the caption but the caption displayed in the text box isn't updating correctly.

Steps to reproduce are kind of hard, its very sporadic:

1.  In Windows open terminal, use `python run.py` to start Captioner GUI
2. Open image folder with existing captions
3. Use the Captioner for a while
4. Update previously saved caption and save, caption text file updated
5. Select another image file, then go back to the previously updated one
6. Text in textbox is the older version, not matching the updated caption text file

Will keep trying to see if I can better reproduce it

EDIT: Yep just had it happen again 15 minutes into a session of updating a folder of existing captions so I'm not going crazy.

**Comment by CypherpunkSamurai** [comment]
Issue confirmed and fixed. Next update will bring changes to master 🚀 

Thanks a lot for the report 😄
